/*
    This file was automatically generated by Studio 3T.

    MongoDB Source Collection: `3d-mall.orders`

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `orders`;
CREATE TABLE `orders` (
    `__v` INTEGER,
    `_id` VARBINARY(12) NOT NULL,
    `address` LONGTEXT,
    `imgsrc` LONGTEXT,
    `name` LONGTEXT,
    `num` INTEGER,
    `phone` LONGTEXT,
    `price` INTEGER,
    `time` LONGTEXT,
    `title` LONGTEXT,
    `totalPrice` INTEGER,
    `username` LONGTEXT,
    PRIMARY KEY (`_id`)
) CHARSET=utf8;

INSERT INTO `orders` (`__v`, `_id`, `address`, `imgsrc`, `name`, `num`, `phone`, `price`, `time`, `title`, `totalPrice`, `username`)
    VALUES
        (0, x'6411D85E5B6D8A0EB9F5701E', '地址地址地址地址地址地址', './imgs/bag.png', '催眠师', 1, '18923583333', 17899, '2023-3-15 22:38', 'GUCCI 古驰新款女包', 17899, 'user1');
INSERT INTO `orders` (`__v`, `_id`, `address`, `imgsrc`, `name`, `num`, `phone`, `price`, `time`, `title`, `totalPrice`, `username`)
    VALUES
        (0, x'6411D85E5B6D8A0EB9F57020', '地址地址地址地址地址地址', './imgs/macpro.jpg', '催眠师', 1, '18923583333', 25899, '2023-3-15 22:38', 'Macbook Pro', 25899, 'user1');
INSERT INTO `orders` (`__v`, `_id`, `address`, `imgsrc`, `name`, `num`, `phone`, `price`, `time`, `title`, `totalPrice`, `username`)
    VALUES
        (0, x'6411E2A35B6D8A0EB9F57024', '地址地址地址地址地址地址', './imgs/bag.png', '催眠师', 1, '18923583333', 17899, '2023-3-15 23:22', 'GUCCI 古驰新款女包', 17899, 'user1');
INSERT INTO `orders` (`__v`, `_id`, `address`, `imgsrc`, `name`, `num`, `phone`, `price`, `time`, `title`, `totalPrice`, `username`)
    VALUES
        (0, x'6411E2A35B6D8A0EB9F57026', '地址地址地址地址地址地址', './imgs/macpro.jpg', '催眠师', 1, '18923583333', 25899, '2023-3-15 23:22', 'Macbook Pro', 25899, 'user1');
INSERT INTO `orders` (`__v`, `_id`, `address`, `imgsrc`, `name`, `num`, `phone`, `price`, `time`, `title`, `totalPrice`, `username`)
    VALUES
        (0, x'6411E2A35B6D8A0EB9F57028', '地址地址地址地址地址地址', './imgs/womenshoes.jpg', '催眠师', 1, '18923583333', 17899, '2023-3-15 23:22', '水晶凉鞋女细跟', 17899, 'user1');
INSERT INTO `orders` (`__v`, `_id`, `address`, `imgsrc`, `name`, `num`, `phone`, `price`, `time`, `title`, `totalPrice`, `username`)
    VALUES
        (0, x'6411E2A95B6D8A0EB9F5702A', '地址地址地址地址地址地址', './imgs/bag.png', '催眠师', 1, '18923583333', 17899, '2023-3-15 23:22', 'GUCCI 古驰新款女包', 17899, 'user1');
INSERT INTO `orders` (`__v`, `_id`, `address`, `imgsrc`, `name`, `num`, `phone`, `price`, `time`, `title`, `totalPrice`, `username`)
    VALUES
        (0, x'6411E2A95B6D8A0EB9F5702C', '地址地址地址地址地址地址', './imgs/macpro.jpg', '催眠师', 1, '18923583333', 25899, '2023-3-15 23:22', 'Macbook Pro', 25899, 'user1');
INSERT INTO `orders` (`__v`, `_id`, `address`, `imgsrc`, `name`, `num`, `phone`, `price`, `time`, `title`, `totalPrice`, `username`)
    VALUES
        (0, x'6411E2A95B6D8A0EB9F5702E', '地址地址地址地址地址地址', './imgs/womenshoes.jpg', '催眠师', 1, '18923583333', 17899, '2023-3-15 23:22', '水晶凉鞋女细跟', 17899, 'user1');
INSERT INTO `orders` (`__v`, `_id`, `address`, `imgsrc`, `name`, `num`, `phone`, `price`, `time`, `title`, `totalPrice`, `username`)
    VALUES
        (0, x'6411E2AD5B6D8A0EB9F57030', '地址地址地址地址地址地址', './imgs/bag.png', '催眠师', 2, '18923583333', 17899, '2023-3-15 23:22', 'GUCCI 古驰新款女包', 35798, 'user1');
INSERT INTO `orders` (`__v`, `_id`, `address`, `imgsrc`, `name`, `num`, `phone`, `price`, `time`, `title`, `totalPrice`, `username`)
    VALUES
        (0, x'6411E2AD5B6D8A0EB9F57032', '地址地址地址地址地址地址', './imgs/macpro.jpg', '催眠师', 2, '18923583333', 25899, '2023-3-15 23:22', 'Macbook Pro', 51798, 'user1');
INSERT INTO `orders` (`__v`, `_id`, `address`, `imgsrc`, `name`, `num`, `phone`, `price`, `time`, `title`, `totalPrice`, `username`)
    VALUES
        (0, x'6411E2AD5B6D8A0EB9F57034', '地址地址地址地址地址地址', './imgs/womenshoes.jpg', '催眠师', 2, '18923583333', 17899, '2023-3-15 23:22', '水晶凉鞋女细跟', 35798, 'user1');
INSERT INTO `orders` (`__v`, `_id`, `address`, `imgsrc`, `name`, `num`, `phone`, `price`, `time`, `title`, `totalPrice`, `username`)
    VALUES
        (0, x'6411E2B25B6D8A0EB9F57036', '地址地址地址地址地址地址', './imgs/bag.png', '催眠师', 4, '18923583333', 17899, '2023-3-15 23:22', 'GUCCI 古驰新款女包', 71596, 'user1');
INSERT INTO `orders` (`__v`, `_id`, `address`, `imgsrc`, `name`, `num`, `phone`, `price`, `time`, `title`, `totalPrice`, `username`)
    VALUES
        (0, x'6411E2B25B6D8A0EB9F57038', '地址地址地址地址地址地址', './imgs/macpro.jpg', '催眠师', 1, '18923583333', 25899, '2023-3-15 23:22', 'Macbook Pro', 25899, 'user1');
INSERT INTO `orders` (`__v`, `_id`, `address`, `imgsrc`, `name`, `num`, `phone`, `price`, `time`, `title`, `totalPrice`, `username`)
    VALUES
        (0, x'6411E2B25B6D8A0EB9F5703A', '地址地址地址地址地址地址', './imgs/womenshoes.jpg', '催眠师', 6, '18923583333', 17899, '2023-3-15 23:22', '水晶凉鞋女细跟', 107394, 'user1');
INSERT INTO `orders` (`__v`, `_id`, `address`, `imgsrc`, `name`, `num`, `phone`, `price`, `time`, `title`, `totalPrice`, `username`)
    VALUES
        (0, x'6411E2B75B6D8A0EB9F5703C', '地址地址地址地址地址地址', './imgs/bag.png', '催眠师', 3, '18923583333', 17899, '2023-3-15 23:22', 'GUCCI 古驰新款女包', 53697, 'user1');
INSERT INTO `orders` (`__v`, `_id`, `address`, `imgsrc`, `name`, `num`, `phone`, `price`, `time`, `title`, `totalPrice`, `username`)
    VALUES
        (0, x'6411E2B75B6D8A0EB9F5703E', '地址地址地址地址地址地址', './imgs/macpro.jpg', '催眠师', 2, '18923583333', 25899, '2023-3-15 23:22', 'Macbook Pro', 51798, 'user1');
INSERT INTO `orders` (`__v`, `_id`, `address`, `imgsrc`, `name`, `num`, `phone`, `price`, `time`, `title`, `totalPrice`, `username`)
    VALUES
        (0, x'6411E2B75B6D8A0EB9F57040', '地址地址地址地址地址地址', './imgs/womenshoes.jpg', '催眠师', 1, '18923583333', 17899, '2023-3-15 23:22', '水晶凉鞋女细跟', 17899, 'user1');
INSERT INTO `orders` (`__v`, `_id`, `address`, `imgsrc`, `name`, `num`, `phone`, `price`, `time`, `title`, `totalPrice`, `username`)
    VALUES
        (0, x'6416B80490F181B72F1932D3', '北京理工大学珠海学院5栋', './imgs/bag.png', '陈梦殊', 1, '18923587457', 17899, '2023-3-19 15:21', 'GUCCI 古驰新款女包', 17899, 'user1');
INSERT INTO `orders` (`__v`, `_id`, `address`, `imgsrc`, `name`, `num`, `phone`, `price`, `time`, `title`, `totalPrice`, `username`)
    VALUES
        (0, x'6416B80490F181B72F1932D5', '北京理工大学珠海学院5栋', './imgs/macpro.jpg', '陈梦殊', 2, '18923587457', 25899, '2023-3-19 15:21', 'Macbook Pro', 51798, 'user1');
INSERT INTO `orders` (`__v`, `_id`, `address`, `imgsrc`, `name`, `num`, `phone`, `price`, `time`, `title`, `totalPrice`, `username`)
    VALUES
        (0, x'6416B80490F181B72F1932D7', '北京理工大学珠海学院5栋', './imgs/womenshoes.jpg', '陈梦殊', 1, '18923587457', 17899, '2023-3-19 15:21', '水晶凉鞋女细跟', 17899, 'user1');
INSERT INTO `orders` (`__v`, `_id`, `address`, `imgsrc`, `name`, `num`, `phone`, `price`, `time`, `title`, `totalPrice`, `username`)
    VALUES
        (0, x'643124AD860402D2A0056FE1', '北京理工大学珠海学院', './imgs/armour.png', '陈梦殊', 2, '18923587457', 700, '2023-4-8 16:24', '盔甲cos服', 1400, 'user1');
INSERT INTO `orders` (`__v`, `_id`, `address`, `imgsrc`, `name`, `num`, `phone`, `price`, `time`, `title`, `totalPrice`, `username`)
    VALUES
        (0, x'643124AD860402D2A0056FE3', '北京理工大学珠海学院', './imgs/overpass.png', '陈梦殊', 1, '18923587457', 50, '2023-4-8 16:24', '立交桥模型', 50, 'user1');
