/*
    This file was automatically generated by Studio 3T.

    MongoDB Source Collection: `3d-mall.goods`

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `goods`;
CREATE TABLE `goods` (
    `_id` VARBINARY(12) NOT NULL,
    `desc.0.content` LONGTEXT,
    `desc.0.title` LONGTEXT,
    `desc.1.content` LONGTEXT,
    `desc.1.title` LONGTEXT,
    `desc.2.content` LONGTEXT,
    `desc.2.title` LONGTEXT,
    `desc.3.content` LONGTEXT,
    `desc.3.title` LONGTEXT,
    `id` DOUBLE,
    `imgsrc` LONGTEXT,
    `modelName` LONGTEXT,
    `modelPath` LONGTEXT,
    `price` DOUBLE,
    `title` LONGTEXT,
    `type` LONGTEXT,
    PRIMARY KEY (`_id`)
) CHARSET=utf8;

INSERT INTO `goods` (`_id`, `desc.0.content`, `desc.0.title`, `desc.1.content`, `desc.1.title`, `desc.2.content`, `desc.2.title`, `desc.3.content`, `desc.3.title`, `id`, `imgsrc`, `modelName`, `modelPath`, `price`, `title`, `type`)
    VALUES
        (x'6422B393741CCB4A4007FF66', '该系列手袋同时推出摩登廓形的水桶包款式', '与一款全新的邮差包设计。', 'Gucci 1955马衔扣系列手袋延续经典手袋线条与造型', '向60年前古驰的经典手袋致敬。', '搭配可调节长度的肩带，肩背或斜挎皆宜。', '手袋结构设计精巧', '标志性的马衔扣设计源于马术运动，由金属双环和一条衔链组合而成。', 'GUCCI 1955马衔扣系列手袋', 7589.0, './imgs/bag.png', 'bag2.glb', './files/gltf/', 17899.0, 'GUCCI 古驰新款女包', 'clothing');
INSERT INTO `goods` (`_id`, `desc.0.content`, `desc.0.title`, `desc.1.content`, `desc.1.title`, `desc.2.content`, `desc.2.title`, `desc.3.content`, `desc.3.title`, `id`, `imgsrc`, `modelName`, `modelPath`, `price`, `title`, `type`)
    VALUES
        (x'6422B393741CCB4A4007FF67', '带来颠覆性表现和惊人续航', '超高速M1 Pro和M1 Max芯片', 'Macbookpro各类强大端口也都整装就位', '炫目的Liquid视网膜XDR显示屏', '无论是剪辑8K视频、编译代码都能随时随地轻松搞定', '战力更猛，耐力也更强！', '图形处理器速度最高提升至4倍，机器学习性能提升至5倍', 'Pro到MAX，霸气不封顶', 7590.0, './imgs/macpro.jpg', 'Macbookpro2.glb', './files/gltf/', 25899.0, 'Macbook Pro', 'office');
INSERT INTO `goods` (`_id`, `desc.0.content`, `desc.0.title`, `desc.1.content`, `desc.1.title`, `desc.2.content`, `desc.2.title`, `desc.3.content`, `desc.3.title`, `id`, `imgsrc`, `modelName`, `modelPath`, `price`, `title`, `type`)
    VALUES
        (x'6422B393741CCB4A4007FF68', '性感潮品、优雅轻淑范！', '白变女神季', '手感光滑、富有弹性、舒适一整天', '舒适、焕新', '水晶搭配金属，凸显柔美气质', '个性、魅力', '每一处的细节，都很到位!', '全透、高端水晶', 7591.0, './imgs/womenshoes.jpg', 'shoes.glb', './files/gltf/', 17899.0, '水晶凉鞋女细跟', 'clothing');
INSERT INTO `goods` (`_id`, `desc.0.content`, `desc.0.title`, `desc.1.content`, `desc.1.title`, `desc.2.content`, `desc.2.title`, `desc.3.content`, `desc.3.title`, `id`, `imgsrc`, `modelName`, `modelPath`, `price`, `title`, `type`)
    VALUES
        (x'64243AA7C023D56C648E3448', '童年的回忆', '婴儿洗澡时的最佳伴侣', 'Macbookpro各类强大端口也都整装就位', '炫目的Liquid视网膜XDR显示屏', '无论是剪辑8K视频、编译代码都能随时随地轻松搞定', '战力更猛，耐力也更强！', '图形处理器速度最高提升至4倍，机器学习性能提升至5倍', 'Pro到MAX，霸气不封顶', 7592.0, './imgs/duck.png', 'Duck.glb', './files/gltf/', 50.0, '鸭子玩具', 'toy');
INSERT INTO `goods` (`_id`, `desc.0.content`, `desc.0.title`, `desc.1.content`, `desc.1.title`, `desc.2.content`, `desc.2.title`, `desc.3.content`, `desc.3.title`, `id`, `imgsrc`, `modelName`, `modelPath`, `price`, `title`, `type`)
    VALUES
        (x'6426829B741CCB2078F8255F', '让你的客厅更加舒适', '白色休闲椅', NULL, NULL, NULL, NULL, NULL, NULL, 7601.0, './imgs/loungeChair.png', 'loungeChair.glb', './files/gltf/', 600.0, '白色休闲椅', 'furniture');
INSERT INTO `goods` (`_id`, `desc.0.content`, `desc.0.title`, `desc.1.content`, `desc.1.title`, `desc.2.content`, `desc.2.title`, `desc.3.content`, `desc.3.title`, `id`, `imgsrc`, `modelName`, `modelPath`, `price`, `title`, `type`)
    VALUES
        (x'64268497741CCB2078F82560', '培养对建筑的敏锐嗅觉', '极具设计感的立交桥模型', NULL, NULL, NULL, NULL, NULL, NULL, 7594.0, './imgs/overpass.png', 'overpass.gltf', './files/gltf/', 50.0, '立交桥模型', 'toy');
INSERT INTO `goods` (`_id`, `desc.0.content`, `desc.0.title`, `desc.1.content`, `desc.1.title`, `desc.2.content`, `desc.2.title`, `desc.3.content`, `desc.3.title`, `id`, `imgsrc`, `modelName`, `modelPath`, `price`, `title`, `type`)
    VALUES
        (x'64268CA6741CCB2078F82562', '让您的步伐轻盈舒适', '极具运动感的透气跑鞋', NULL, NULL, NULL, NULL, NULL, NULL, 7595.0, './imgs/MaterialsVariantsShoe.jpg', 'MaterialsVariantsShoe.glb', './files/gltf/', 850.0, 'IIIFORM跑鞋', 'clothing');
INSERT INTO `goods` (`_id`, `desc.0.content`, `desc.0.title`, `desc.1.content`, `desc.1.title`, `desc.2.content`, `desc.2.title`, `desc.3.content`, `desc.3.title`, `id`, `imgsrc`, `modelName`, `modelPath`, `price`, `title`, `type`)
    VALUES
        (x'642699EA741CCB0A4CDB0AC1', '让您在冬天仍然舒适办公', '加绒材质的摊子', NULL, NULL, NULL, NULL, NULL, NULL, 7596.0, './imgs/DragonAttenuation.jpg', 'DragonAttenuation.glb', './files/gltf/', 50.0, '办公毯子', 'office');
INSERT INTO `goods` (`_id`, `desc.0.content`, `desc.0.title`, `desc.1.content`, `desc.1.title`, `desc.2.content`, `desc.2.title`, `desc.3.content`, `desc.3.title`, `id`, `imgsrc`, `modelName`, `modelPath`, `price`, `title`, `type`)
    VALUES
        (x'6426AB8C741CCB0A4CDB0AC3', '材质安全，放心把玩！', '复古感路灯玩具', NULL, NULL, NULL, NULL, NULL, NULL, 7597.0, './imgs/Lantern.jpg', 'Lantern.glb', './files/gltf/', 50.0, '路灯模型玩具', 'toy');
INSERT INTO `goods` (`_id`, `desc.0.content`, `desc.0.title`, `desc.1.content`, `desc.1.title`, `desc.2.content`, `desc.2.title`, `desc.3.content`, `desc.3.title`, `id`, `imgsrc`, `modelName`, `modelPath`, `price`, `title`, `type`)
    VALUES
        (x'6426AE9F741CCB0A4CDB0AC4', '让您的豪宅愈加富丽堂皇', '亿万年的等待，只为见你', NULL, NULL, NULL, NULL, NULL, NULL, 7597.0, './imgs/MosquitoInAmber.jpg', 'MosquitoInAmber.glb', './files/gltf/', 50000.0, '黄色琥珀', 'furniture');
INSERT INTO `goods` (`_id`, `desc.0.content`, `desc.0.title`, `desc.1.content`, `desc.1.title`, `desc.2.content`, `desc.2.title`, `desc.3.content`, `desc.3.title`, `id`, `imgsrc`, `modelName`, `modelPath`, `price`, `title`, `type`)
    VALUES
        (x'64281105741CCB3D080E79BE', '陪伴你的睡眠', '轻色调床头柜', NULL, NULL, NULL, NULL, NULL, NULL, 7597.0, './imgs/nightstand1.png', 'nightstand1.glb', './files/gltf/', 600.0, '白色床头柜', 'furniture');
INSERT INTO `goods` (`_id`, `desc.0.content`, `desc.0.title`, `desc.1.content`, `desc.1.title`, `desc.2.content`, `desc.2.title`, `desc.3.content`, `desc.3.title`, `id`, `imgsrc`, `modelName`, `modelPath`, `price`, `title`, `type`)
    VALUES
        (x'64281A53741CCB3D080E79C0', '点缀你的卧室', '圆形床头柜', NULL, NULL, NULL, NULL, NULL, NULL, 7599.0, './imgs/nightstand2.jpg', 'nightstand2.glb', './files/gltf/', 600.0, '白色床头柜', 'furniture');
INSERT INTO `goods` (`_id`, `desc.0.content`, `desc.0.title`, `desc.1.content`, `desc.1.title`, `desc.2.content`, `desc.2.title`, `desc.3.content`, `desc.3.title`, `id`, `imgsrc`, `modelName`, `modelPath`, `price`, `title`, `type`)
    VALUES
        (x'64281DAC741CCB3D080E79C7', '营造更好的办公环境', '白色办公桌', NULL, NULL, NULL, NULL, NULL, NULL, 7600.0, './imgs/desk1.png', 'desk1.glb', './files/gltf/', 1600.0, '白色办公桌', 'office');
INSERT INTO `goods` (`_id`, `desc.0.content`, `desc.0.title`, `desc.1.content`, `desc.1.title`, `desc.2.content`, `desc.2.title`, `desc.3.content`, `desc.3.title`, `id`, `imgsrc`, `modelName`, `modelPath`, `price`, `title`, `type`)
    VALUES
        (x'642EE32AE3CF8935D89464A3', '成为雪地上的一抹亮丽白色', '简约风滑雪板', NULL, NULL, NULL, NULL, NULL, NULL, 7602.0, './imgs/skateboard.png', 'skateboard.glb', './files/gltf/', 300.0, '滑雪板', 'toy');
INSERT INTO `goods` (`_id`, `desc.0.content`, `desc.0.title`, `desc.1.content`, `desc.1.title`, `desc.2.content`, `desc.2.title`, `desc.3.content`, `desc.3.title`, `id`, `imgsrc`, `modelName`, `modelPath`, `price`, `title`, `type`)
    VALUES
        (x'642EF1C6E3CF8935D89464A5', '孩子的最佳伴侣', '消防车玩具模型', NULL, NULL, NULL, NULL, NULL, NULL, 7603.0, './imgs/cartoon_fire_truck.png', 'cartoon_fire_truck.glb', './files/gltf/', 200.0, '消防车玩具', 'toy');
INSERT INTO `goods` (`_id`, `desc.0.content`, `desc.0.title`, `desc.1.content`, `desc.1.title`, `desc.2.content`, `desc.2.title`, `desc.3.content`, `desc.3.title`, `id`, `imgsrc`, `modelName`, `modelPath`, `price`, `title`, `type`)
    VALUES
        (x'6430420B741CCB6684D16E69', '孩子的科幻启蒙', '仿真激光枪', NULL, NULL, NULL, NULL, NULL, NULL, 7604.0, './imgs/sci-fi_rifle.png', 'sci-fi_rifle.glb', './files/gltf/', 700.0, '激光枪', 'toy');
INSERT INTO `goods` (`_id`, `desc.0.content`, `desc.0.title`, `desc.1.content`, `desc.1.title`, `desc.2.content`, `desc.2.title`, `desc.3.content`, `desc.3.title`, `id`, `imgsrc`, `modelName`, `modelPath`, `price`, `title`, `type`)
    VALUES
        (x'6430458D741CCB6684D16E6A', '霸气外露', '盔甲cos服', NULL, NULL, NULL, NULL, NULL, NULL, 7605.0, './imgs/armour.png', 'armour.glb', './files/gltf/', 700.0, '盔甲cos服', 'clothing');
INSERT INTO `goods` (`_id`, `desc.0.content`, `desc.0.title`, `desc.1.content`, `desc.1.title`, `desc.2.content`, `desc.2.title`, `desc.3.content`, `desc.3.title`, `id`, `imgsrc`, `modelName`, `modelPath`, `price`, `title`, `type`)
    VALUES
        (x'64310731741CCB279CA2BB10', '带来极致的视听体验', '超高显2K屏', NULL, NULL, NULL, NULL, NULL, NULL, 7597.0, './imgs/tablet.png', 'tablet.glb', './files/gltf/', 8899.0, '平板电脑', 'office');
INSERT INTO `goods` (`_id`, `desc.0.content`, `desc.0.title`, `desc.1.content`, `desc.1.title`, `desc.2.content`, `desc.2.title`, `desc.3.content`, `desc.3.title`, `id`, `imgsrc`, `modelName`, `modelPath`, `price`, `title`, `type`)
    VALUES
        (x'64310986741CCB279CA2BB11', '老年人的伴侣', '传统32bit收音机', NULL, NULL, NULL, NULL, NULL, NULL, 7610.0, './imgs/radio.png', 'radio.glb', './files/gltf/', 140.0, '传统32bit收音机', 'furniture');
INSERT INTO `goods` (`_id`, `desc.0.content`, `desc.0.title`, `desc.1.content`, `desc.1.title`, `desc.2.content`, `desc.2.title`, `desc.3.content`, `desc.3.title`, `id`, `imgsrc`, `modelName`, `modelPath`, `price`, `title`, `type`)
    VALUES
        (x'643129F1741CCB279CA2BB1A', '小贵，但是好用', '精致而方便的水晶果盘', NULL, NULL, NULL, NULL, NULL, NULL, 7593.0, './imgs/IridescentDishWithOlives.jpg', 'IridescentDishWithOlives.glb', './files/gltf/', 50.0, '水晶果盘', 'furniture');
