/*
    This file was automatically generated by Studio 3T.

    MongoDB Source Collection: `3d-mall.users`

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
    `__v` INTEGER,
    `_id` VARBINARY(12) NOT NULL,
    `password` LONGTEXT,
    `username` LONGTEXT,
    PRIMARY KEY (`_id`)
) CHARSET=utf8;

INSERT INTO `users` (`__v`, `_id`, `password`, `username`)
    VALUES
        (0, x'640EBBFD2C839E6C9C85CA07', '111', 'user1');
INSERT INTO `users` (`__v`, `_id`, `password`, `username`)
    VALUES
        (0, x'641036E28D2C3BCE314CF14B', '222', 'user2');
